fixtures:
  repositories:
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib'
    xinetd:
      repo: 'git://github.com/puppetlabs/puppetlabs-xinetd'
      ref:  'e84f34f'

  symlinks:
    tftp: "#{source_dir}"
